<a href="https://colab.research.google.com/github/Tejvir007/Deep-Learning/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1:

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

In [18]:
# Parameters for dataset generation
num_samples = 2000   # Number of samples (rows)
num_features = 20    # Number of features (columns)
num_classes = 3      # Number of classes
class_sep = 1.0      # Class separation
random_state = 42    # Random state for reproducibility
flip_y = 0.01        # Noise level (percentage of labels to flip)

# Generate a synthetic dataset
X, y = make_classification(n_samples=num_samples,
                           n_features=num_features,
                           n_informative=num_features - 2,
                           n_redundant=2,
                           n_clusters_per_class=1,
                           n_classes=num_classes,
                           class_sep=class_sep,
                           flip_y=flip_y,
                           random_state=random_state)

# Convert to DataFrame for easier manipulation if needed
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(1, num_features + 1)])
df['target'] = y
df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -0.891714   2.143801   3.043796   3.578512  -4.314302  -5.979089   
1  -2.865702   1.209591   0.809375  -1.357679  -1.675274  -0.853139   
2  -2.654971  -1.820009  -1.984135   0.164040   1.164334  -0.832851   
3  -1.372404   0.270253  -1.390480  -3.770606   1.279341  -0.718266   
4   3.176393   0.783989  -1.498911  -1.282004   1.432893  -0.821655   

   feature_7  feature_8  feature_9  feature_10  ...  feature_12  feature_13  \
0   3.411947   7.041184  -0.276279   -5.141322  ...   -3.540606  -14.312341   
1  -1.749236   3.513785  -0.163565    0.068246  ...    2.128961   -0.334424   
2   0.837058   3.585625  -0.386588    1.611094  ...    1.689347   -2.411027   
3  -5.490762  -0.923265   4.089694   -2.729973  ...   -0.011855   -7.447057   
4  -5.263793  -0.633427   2.326336   -2.870295  ...    2.078699   -3.238077   

   feature_14  feature_15  feature_16  feature_17  feature_18  feature_19  \
0   -0.106219    1.513496   -1.886513    1.120863   -6.184435    0.385063   
1    2.081106    2.960085    0.658716    0.121173   -3.653258    2.889425   
2   -0.646337   -0.084181   -2.424869    1.983391   -1.350010   -0.166226   
3   -3.986637    0.889862   -2.693529    0.453754   -5.719562    4.180654   
4   -1.912404   -2.609660    2.770548   -3.541459   -1.092140   -0.382778   

   feature_20  target  
0   -4.355327       0  
1    0.405151       1  
2   -1.968121       0  
3    3.904454       1  
4    0.884015       1  

[5 rows x 21 columns]

In [3]:
# Load the dataset
X = df.drop('target', axis=1).values
y = df['target'].values

# Convert labels to one-hot encoding
y_one_hot = tf.keras.utils.to_categorical(y, num_classes)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y_one_hot, test_size=0.2, random_state=random_state)

In [4]:

# Define the MLP model
model = Sequential()
model.add(Dense(64, input_dim=num_features, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
# Train the model
model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_val, y_val))

Epoch 1/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4892 - loss: 0.9914 - val_accuracy: 0.8625 - val_loss: 0.4368
Epoch 2/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8963 - loss: 0.3443 - val_accuracy: 0.9075 - val_loss: 0.2929
Epoch 3/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9392 - loss: 0.2131 - val_accuracy: 0.9225 - val_loss: 0.2445
Epoch 4/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9519 - loss: 0.1614 - val_accuracy: 0.9225 - val_loss: 0.2300
Epoch 5/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9666 - loss: 0.1168 - val_accuracy: 0.9275 - val_loss: 0.2133
Epoch 6/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9671 - loss: 0.1101 - val_accuracy: 0.9350 - val_loss: 0.2041
Epoch 7/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9778 - loss: 0.0890 - val_accuracy: 0.9450 - val_loss: 0.1914
Epoch 8/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9814 - loss: 0.0818 - val_accuracy: 0.9550 - val_loss:

In [16]:

val_loss, val_accuracy = model.evaluate(X_val, y_val)
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")


13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9650 - loss: 0.1325 
Validation Accuracy: 95.75%


In [7]:
# Predict on the validation set
y_val_pred = model.predict(X_val)
y_val_pred_classes = np.argmax(y_val_pred, axis=1)
y_val_true_classes = np.argmax(y_val, axis=1)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_val_true_classes, y_val_pred_classes)
print("Confusion Matrix:")
print(conf_matrix)

# Also print the accuracy score from sklearn for reference
accuracy = accuracy_score(y_val_true_classes, y_val_pred_classes)
print(f"Accuracy Score (sklearn): {accuracy * 100:.2f}%")

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Confusion Matrix:
[[122   2   8]
 [  1 126   5]
 [  1   0 135]]
Accuracy Score (sklearn): 95.75%


Question 2:

In [8]:
import numpy as np

In [9]:
# Given confusion matrix
confusion_matrix = np.array([
    [27, 5, 2],   # Class 1 Actual
    [10, 7, 0],   # Class 2 Actual
    [2, 0, 31]    # Class 3 Actual
])

In [10]:
# Initialize variables to store results
precision = []
recall = []
f1_score = []
accuracy = []

In [11]:
# Number of classes
num_classes = confusion_matrix.shape[0]

In [12]:
# Calculate metrics for each class
for i in range(num_classes):
    TP = confusion_matrix[i, i]
    FP = sum(confusion_matrix[:, i]) - TP
    FN = sum(confusion_matrix[i, :]) - TP
    TN = sum(sum(confusion_matrix)) - (TP + FP + FN)

    precision_i = TP / (TP + FP) if (TP + FP) != 0 else 0
    recall_i = TP / (TP + FN) if (TP + FN) != 0 else 0
    f1_score_i = 2 * (precision_i * recall_i) / (precision_i + recall_i) if (precision_i + recall_i) != 0 else 0
    accuracy_i = (TP + TN) / (TP + FP + FN + TN)

    precision.append(precision_i)
    recall.append(recall_i)
    f1_score.append(f1_score_i)
    accuracy.append(accuracy_i)

In [13]:
# Print the results for each class
for i in range(num_classes):
    print(f'Class {i+1}:')
    print(f'  Precision: {precision[i]:.2f}')
    print(f'  Recall: {recall[i]:.2f}')
    print(f'  F1-Score: {f1_score[i]:.2f}')
    print(f'  Accuracy: {accuracy[i]:.2f}')
    print()

Class 1:
  Precision: 0.69
  Recall: 0.79
  F1-Score: 0.74
  Accuracy: 0.77

Class 2:
  Precision: 0.58
  Recall: 0.41
  F1-Score: 0.48
  Accuracy: 0.82

Class 3:
  Precision: 0.94
  Recall: 0.94
  F1-Score: 0.94
  Accuracy: 0.95

