<a href="https://colab.research.google.com/github/Tejvir007/Deep-Learning/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

In [2]:
# Parameters for dataset generation
num_samples = 2000   # Number of samples (rows)
num_features = 20    # Number of features (columns)
num_classes = 3      # Number of classes
class_sep = 1.0      # Class separation
random_state = 42    # Random state for reproducibility
flip_y = 0.01        # Noise level (percentage of labels to flip)

# Generate a synthetic dataset
X, y = make_classification(n_samples=num_samples,
                           n_features=num_features,
                           n_informative=num_features - 2,
                           n_redundant=2,
                           n_clusters_per_class=1,
                           n_classes=num_classes,
                           class_sep=class_sep,
                           flip_y=flip_y,
                           random_state=random_state)

# Convert to DataFrame for easier manipulation if needed
df = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(1, num_features + 1)])
df['target'] = y

In [3]:
# Load the dataset
X = df.drop('target', axis=1).values
y = df['target'].values

# Convert labels to one-hot encoding
y_one_hot = tf.keras.utils.to_categorical(y, num_classes)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y_one_hot, test_size=0.2, random_state=random_state)

In [4]:

# Define the MLP model
model = Sequential()
model.add(Dense(64, input_dim=num_features, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
# Train the model
model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_val, y_val))

Epoch 1/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4892 - loss: 0.9914 - val_accuracy: 0.8625 - val_loss: 0.4368
Epoch 2/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8963 - loss: 0.3443 - val_accuracy: 0.9075 - val_loss: 0.2929
Epoch 3/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9392 - loss: 0.2131 - val_accuracy: 0.9225 - val_loss: 0.2445
Epoch 4/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9519 - loss: 0.1614 - val_accuracy: 0.9225 - val_loss: 0.2300
Epoch 5/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9666 - loss: 0.1168 - val_accuracy: 0.9275 - val_loss: 0.2133
Epoch 6/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9671 - loss: 0.1101 - val_accuracy: 0.9350 - val_loss: 0.2041
Epoch 7/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9778 - loss: 0.0890 - val_accuracy: 0.9450 - val_loss: 0.1914
Epoch 8/30
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9814 - loss: 0.0818 - val_accuracy: 0.9550 - val_loss:

In [6]:
# Evaluate the model
val_loss, val_accuracy = model.evaluate(X_val, y_val)
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")


13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9650 - loss: 0.1325 
Validation Accuracy: 95.75%


In [7]:
# Predict on the validation set
y_val_pred = model.predict(X_val)
y_val_pred_classes = np.argmax(y_val_pred, axis=1)
y_val_true_classes = np.argmax(y_val, axis=1)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_val_true_classes, y_val_pred_classes)
print("Confusion Matrix:")
print(conf_matrix)

# Also print the accuracy score from sklearn for reference
accuracy = accuracy_score(y_val_true_classes, y_val_pred_classes)
print(f"Accuracy Score (sklearn): {accuracy * 100:.2f}%")

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Confusion Matrix:
[[122   2   8]
 [  1 126   5]
 [  1   0 135]]
Accuracy Score (sklearn): 95.75%
